###                             -*-Makefile-*-
### Makefile for modular pencil code -- local part
### Included by `Makefile'
###

MPICOMM =    mpicomm
#IO      =   io_mpi2
IO      =  io_dist

HYDRO   =   hydro
DENSITY =   density
SHEAR   =   shear

SHOCK = shock_highorder

DUSTDENSITY = dustdensity
DUSTVELOCITY = dustvelocity

REAL_PRECISION = double
